<a href="https://colab.research.google.com/github/rosemarythomas994/pandaslearning/blob/main/home.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor


data = pd.read_csv(r'/content/drive/MyDrive/colab/Housing.csv',encoding='ISO-8859-1')
data

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [ ]:
pd.options.display.max_rows=3000

In [ ]:
data.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [ ]:
data.head()

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0  13300000  7420         4          2        3         1          0   
1  12250000  8960         4          4        4         1          0   
2  12250000  9960         3          2        2         1          0   
3  12215000  7500         4          2        2         1          0   
4  11410000  7420         4          1        2         1          1   

   basement  hotwaterheating  airconditioning  parking  prefarea  \
0         0                0                1        2         1   
1         0                0                1        3         0   
2         1                0                0        2         1   
3         1                0                1        3         1   
4         1                0                1        2         0   

   furnishingstatus  
0                 0  
1                 0  
2                 1  
3                 0  
4                 0

In [ ]:
data.head(10)

price   area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0  13300000   7420         4          2        3         1          0   
1  12250000   8960         4          4        4         1          0   
2  12250000   9960         3          2        2         1          0   
3  12215000   7500         4          2        2         1          0   
4  11410000   7420         4          1        2         1          1   
5  10850000   7500         3          3        1         1          0   
6  10150000   8580         4          3        4         1          0   
7  10150000  16200         5          3        2         1          0   
8   9870000   8100         4          1        2         1          1   
9   9800000   5750         3          2        4         1          1   

   basement  hotwaterheating  airconditioning  parking  prefarea  \
0         0                0                1        2         1   
1         0                0                1        3         0   
2         1                0                0        2         1   
3         1                0                1        3         1   
4         1                0                1        2         0   
5         1                0                1        2         1   
6         0                0                1        2         1   
7         0                0                0        0         0   
8         1                0                1        2         1   
9         0                0                1        1         1   

   furnishingstatus  
0                 0  
1                 0  
2                 1  
3                 0  
4                 0  
5                 1  
6                 1  
7                 2  
8                 0  
9                 2

In [ ]:
data.tail()

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
540  1820000  3000         2          1        1         1          0   
541  1767150  2400         3          1        1         0          0   
542  1750000  3620         2          1        1         1          0   
543  1750000  2910         3          1        1         0          0   
544  1750000  3850         3          1        2         1          0   

     basement  hotwaterheating  airconditioning  parking  prefarea  \
540         1                0                0        2         0   
541         0                0                0        0         0   
542         0                0                0        0         0   
543         0                0                0        0         0   
544         0                0                0        0         0   

     furnishingstatus  
540                 2  
541                 1  
542                 2  
543                 0  
544                 2

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    int64
 6   guestroom         545 non-null    int64
 7   basement          545 non-null    int64
 8   hotwaterheating   545 non-null    int64
 9   airconditioning   545 non-null    int64
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    int64
 12  furnishingstatus  545 non-null    int64
dtypes: int64(13)
memory usage: 55.5 KB


In [ ]:
data.describe()

price          area    bedrooms   bathrooms     stories  \
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000   
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505   
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492   
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000   
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000   
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000   
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000   
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000   

         mainroad   guestroom    basement  hotwaterheating  airconditioning  \
count  545.000000  545.000000  545.000000       545.000000       545.000000   
mean     0.858716    0.177982    0.350459         0.045872         0.315596   
std      0.348635    0.382849    0.477552         0.209399         0.465180   
min      0.000000    0.000000    0.000000         0.000000         0.000000   
25%      1.000000    0.000000    0.000000         0.000000         0.000000   
50%      1.000000    0.000000    0.000000         0.000000         0.000000   
75%      1.000000    0.000000    1.000000         0.000000         1.000000   
max      1.000000    1.000000    1.000000         1.000000         1.000000   

          parking    prefarea  furnishingstatus  
count  545.000000  545.000000        545.000000  
mean     0.693578    0.234862          1.069725  
std      0.861586    0.424302          0.761373  
min      0.000000    0.000000          0.000000  
25%      0.000000    0.000000          0.000000  
50%      0.000000    0.000000          1.000000  
75%      1.000000    0.000000          2.000000  
max      3.000000    1.000000          2.000000

In [ ]:
data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [ ]:
data.describe()

price          area    bedrooms   bathrooms     stories  \
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000   
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505   
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492   
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000   
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000   
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000   
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000   
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000   

          parking  
count  545.000000  
mean     0.693578  
std      0.861586  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      3.000000

In [ ]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
540    False
541    False
542    False
543    False
544    False
Length: 545, dtype: bool

In [ ]:
data.shape

(545, 13)

In [ ]:
le=LabelEncoder()

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [ ]:
data['mainroad']=le.fit_transform(data['mainroad'])

In [ ]:
data['guestroom']=le.fit_transform(data['guestroom'])
data['basement']=le.fit_transform(data['basement'])
data['hotwaterheating']=le.fit_transform(data['hotwaterheating'])
data['airconditioning']=le.fit_transform(data['airconditioning'])
data['prefarea']=le.fit_transform(data['prefarea'])
data['furnishingstatus']=le.fit_transform(data['furnishingstatus'])

In [ ]:
data

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0    13300000  7420         4          2        3         1          0   
1    12250000  8960         4          4        4         1          0   
2    12250000  9960         3          2        2         1          0   
3    12215000  7500         4          2        2         1          0   
4    11410000  7420         4          1        2         1          1   
..        ...   ...       ...        ...      ...       ...        ...   
540   1820000  3000         2          1        1         1          0   
541   1767150  2400         3          1        1         0          0   
542   1750000  3620         2          1        1         1          0   
543   1750000  2910         3          1        1         0          0   
544   1750000  3850         3          1        2         1          0   

     basement  hotwaterheating  airconditioning  parking  prefarea  \
0           0                0                1        2         1   
1           0                0                1        3         0   
2           1                0                0        2         1   
3           1                0                1        3         1   
4           1                0                1        2         0   
..        ...              ...              ...      ...       ...   
540         1                0                0        2         0   
541         0                0                0        0         0   
542         0                0                0        0         0   
543         0                0                0        0         0   
544         0                0                0        0         0   

     furnishingstatus  
0                   0  
1                   0  
2                   1  
3                   0  
4                   0  
..                ...  
540                 2  
541                 1  
542                 2  
543                 0  
544                 2  

[545 rows x 13 columns]

In [ ]:
x = data.drop(['price'],axis=1)

In [ ]:
x

area  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
0    7420         4          2        3         1          0         0   
1    8960         4          4        4         1          0         0   
2    9960         3          2        2         1          0         1   
3    7500         4          2        2         1          0         1   
4    7420         4          1        2         1          1         1   
..    ...       ...        ...      ...       ...        ...       ...   
540  3000         2          1        1         1          0         1   
541  2400         3          1        1         0          0         0   
542  3620         2          1        1         1          0         0   
543  2910         3          1        1         0          0         0   
544  3850         3          1        2         1          0         0   

     hotwaterheating  airconditioning  parking  prefarea  furnishingstatus  
0                  0                1        2         1                 0  
1                  0                1        3         0                 0  
2                  0                0        2         1                 1  
3                  0                1        3         1                 0  
4                  0                1        2         0                 0  
..               ...              ...      ...       ...               ...  
540                0                0        2         0                 2  
541                0                0        0         0                 1  
542                0                0        0         0                 2  
543                0                0        0         0                 0  
544                0                0        0         0                 2  

[545 rows x 12 columns]

In [ ]:
y =data.price

In [ ]:
y

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...   
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2, random_state=42)

In [ ]:
print(len(xtrain),len(ytrain))
print(len(xtest),len(ytest))

436 436
109 109


In [ ]:
xtrain

area  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
46   6000         3          2        4         1          0         0   
93   7200         3          2        1         1          0         1   
335  3816         2          1        1         1          0         1   
412  2610         3          1        2         1          0         1   
471  3750         3          1        2         1          0         0   
..    ...       ...        ...      ...       ...        ...       ...   
71   6000         4          2        4         1          0         0   
106  5450         4          2        1         1          0         1   
270  4500         3          2        3         1          0         0   
435  4040         2          1        1         1          0         0   
102  5500         3          2        4         1          1         0   

     hotwaterheating  airconditioning  parking  prefarea  furnishingstatus  
46                 0                1        1         0                 0  
93                 0                1        3         0                 1  
335                0                1        2         0                 0  
412                0                0        0         1                 2  
471                0                0        0         0                 2  
..               ...              ...      ...       ...               ...  
71                 0                1        0         0                 2  
106                0                1        0         1                 1  
270                1                0        1         0                 0  
435                0                0        0         0                 2  
102                0                1        1         0                 1  

[436 rows x 12 columns]

In [ ]:
ytrain

46     7525000
93     6300000
335    3920000
412    3430000
471    3010000
        ...   
71     6755000
106    6160000
270    4340000
435    3290000
102    6195000
Name: price, Length: 436, dtype: int64

In [ ]:
#LinearRegression
model = LinearRegression()

In [ ]:
model.fit(xtrain,ytrain)

LinearRegression()

In [ ]:
model.score(xtest,ytest)

0.6494754192267803

In [ ]:
data

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0    13300000  7420         4          2        3         1          0   
1    12250000  8960         4          4        4         1          0   
2    12250000  9960         3          2        2         1          0   
3    12215000  7500         4          2        2         1          0   
4    11410000  7420         4          1        2         1          1   
..        ...   ...       ...        ...      ...       ...        ...   
540   1820000  3000         2          1        1         1          0   
541   1767150  2400         3          1        1         0          0   
542   1750000  3620         2          1        1         1          0   
543   1750000  2910         3          1        1         0          0   
544   1750000  3850         3          1        2         1          0   

     basement  hotwaterheating  airconditioning  parking  prefarea  \
0           0                0                1        2         1   
1           0                0                1        3         0   
2           1                0                0        2         1   
3           1                0                1        3         1   
4           1                0                1        2         0   
..        ...              ...              ...      ...       ...   
540         1                0                0        2         0   
541         0                0                0        0         0   
542         0                0                0        0         0   
543         0                0                0        0         0   
544         0                0                0        0         0   

     furnishingstatus  
0                   0  
1                   0  
2                   1  
3                   0  
4                   0  
..                ...  
540                 2  
541                 1  
542                 2  
543                 0  
544                 2  

[545 rows x 13 columns]

In [ ]:
#model.predict([[7420,4,2,3,1,0,0,0,1,2,1]])
model.predict([[7420,4,2,3,1,	0,0,0,1,2,1,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([8004072.41154001])

In [ ]:
model.predict([[8960,	4,	4,	4,	1,	0,	0,	0,	1,	3,	0,	0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([10563592.0699829])

In [ ]:
model.predict([[9960,	3,	2,	2,	1,	0,	1,	0,	0,	2,	1,	1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([7515542.71619024])

In [ ]:
#LogisticRegression
model1 = LogisticRegression()

In [ ]:
model1.fit(xtrain,ytrain)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
model1.score(xtest,ytest)

0.009174311926605505

In [ ]:
model1.predict([[7420,4,2,3,1,	0,0,0,1,2,1,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([5950000])

In [ ]:
model1.predict([[8960,	4,	4,	4,	1,	0,	0,	0,	1,	3,	0,	0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([6300000])

In [ ]:
# Decision tree



In [ ]:
model2 = DecisionTreeClassifier()
model2.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [ ]:
model2.score(xtest,ytest)

0.009174311926605505

In [ ]:
model2.predict([[7420,4,2,3,1,	0,0,0,1,2,1,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([11410000])

In [ ]:
model2.predict([[8960,	4,	4,	4,	1,	0,	0,	0,	1,	3,	0,	0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([12250000])

In [ ]:
model2.predict([[9960,	3,	2,	2,	1,	0,	1,	0,	0,	2,	1,	1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([5250000])

In [ ]:
#DecisionTreeRegressor
model3 = DecisionTreeRegressor()
model3.fit(xtrain,ytrain)

DecisionTreeRegressor()

In [ ]:
model3.score(xtest,ytest)

0.41828189592185194

In [ ]:
model3.predict([[7420,4,2,3,1,	0,0,0,1,2,1,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([9100000.])

In [ ]:
model3.predict([[8960,	4,	4,	4,	1,	0,	0,	0,	1,	3,	0,	0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([12250000.])

In [ ]:
model3.predict([[9960,	3,	2,	2,	1,	0,	1,	0,	0,	2,	1,	1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([6790000.])

In [ ]:
#RandomForestClassifier()
from sklearn.ensemble import RandomForestClassifier
model4 = RandomForestClassifier()
model4.fit(xtrain,ytrain)

RandomForestClassifier()

In [ ]:
model4.score(xtest,ytest)

0.009174311926605505

In [ ]:
model4.predict([[7420,4,2,3,1,	0,0,0,1,2,1,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([11410000])

In [ ]:
model4.predict([[9960,	3,	2,	2,	1,	0,	1,	0,	0,	2,	1,	1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([5950000])

In [ ]:
model4.predict([[8960,	4,	4,	4,	1,	0,	0,	0,	1,	3,	0,	0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([12250000])

In [ ]:
ytest

316    4060000
77     6650000
360    3710000
90     6440000
493    2800000
        ...   
15     9100000
357    3773000
39     7910000
54     7350000
155    5530000
Name: price, Length: 109, dtype: int64

In [ ]:
from sklearn.metrics import mean_squared_error, explained_variance_score

#ypred = model.predict(xtest)
#ypred = model1.predict(xtest)
ypred = model2.predict(xtest)
ypred

array([ 3990000,  7840000,  3850000,  5740000,  3990000,  4795000,
        3773000,  4550000,  1855000,  2520000,  5250000,  2695000,
        3115000,  3640000,  4865000,  4200000,  3850000,  7420000,
        2870000,  4270000,  5075000,  5950000,  2345000,  2730000,
        6020000,  5250000,  2310000,  3885000,  9870000,  2961000,
        8295000,  3150000,  8463000,  7840000,  2485000,  4480000,
        4900000,  4200000,  3115000,  3885000,  3920000,  2653000,
        7840000,  4585000,  2730000,  4200000,  7560000,  4165000,
        3087000,  2800000,  6895000,  3150000,  5110000,  3990000,
        3500000,  2520000,  5250000,  3430000,  5250000,  3360000,
        5215000,  4200000,  4270000,  4200000,  2870000,  4550000,
        4123000,  3465000,  3500000,  5565000,  3150000,  7840000,
        5110000,  7000000,  2653000,  3500000,  3780000,  5565000,
        3710000,  3010000,  8540000,  4480000,  4060000,  4795000,
        3430000,  3640000,  3465000,  4515000, 11410000,  7700

In [ ]:
ytest

316    4060000
77     6650000
360    3710000
90     6440000
493    2800000
        ...   
15     9100000
357    3773000
39     7910000
54     7350000
155    5530000
Name: price, Length: 109, dtype: int64

In [ ]:
ypred

array([ 3990000,  7840000,  3850000,  5740000,  3990000,  4795000,
        3773000,  4550000,  1855000,  2520000,  5250000,  2695000,
        3115000,  3640000,  4865000,  4200000,  3850000,  7420000,
        2870000,  4270000,  5075000,  5950000,  2345000,  2730000,
        6020000,  5250000,  2310000,  3885000,  9870000,  2961000,
        8295000,  3150000,  8463000,  7840000,  2485000,  4480000,
        4900000,  4200000,  3115000,  3885000,  3920000,  2653000,
        7840000,  4585000,  2730000,  4200000,  7560000,  4165000,
        3087000,  2800000,  6895000,  3150000,  5110000,  3990000,
        3500000,  2520000,  5250000,  3430000,  5250000,  3360000,
        5215000,  4200000,  4270000,  4200000,  2870000,  4550000,
        4123000,  3465000,  3500000,  5565000,  3150000,  7840000,
        5110000,  7000000,  2653000,  3500000,  3780000,  5565000,
        3710000,  3010000,  8540000,  4480000,  4060000,  4795000,
        3430000,  3640000,  3465000,  4515000, 11410000,  7700

In [ ]:
xtest

area  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
316  5900         4          2        2         0          0         1   
77   6500         3          2        3         1          0         0   
360  4040         2          1        1         1          0         0   
90   5000         3          1        2         1          0         0   
493  3960         3          1        1         1          0         0   
..    ...       ...        ...      ...       ...        ...       ...   
15   6000         4          1        2         1          0         1   
357  6930         4          1        2         0          0         0   
39   6000         4          2        4         1          0         0   
54   6000         3          2        2         1          1         0   
155  6100         3          2        1         1          0         1   

     hotwaterheating  airconditioning  parking  prefarea  furnishingstatus  
316                0                0        1         0                 2  
77                 0                1        0         1                 0  
360                0                0        0         0                 1  
90                 0                1        0         0                 1  
493                0                0        0         0                 0  
..               ...              ...      ...       ...               ...  
15                 0                0        2         0                 1  
357                0                0        1         0                 0  
39                 0                1        1         0                 1  
54                 0                1        1         0                 1  
155                0                0        2         1                 0  

[109 rows x 12 columns]

In [ ]:
mse = mean_squared_error(ytest,ypred)
mse

2909066839449.5415

In [ ]:
import math
rmse = math.sqrt(mse)
rmse

1705598.674791213

In [ ]:
evs = explained_variance_score(ytest,ypred)
evs

0.4504043744473065

In [ ]:
cm = confusion_matrix(ytest,ypred)
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]])

In [ ]:
#import seaborn as sns
#sns.heatmap(cm, annot=True)