<a href="https://colab.research.google.com/github/rosemarythomas994/pandaslearning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

NumPy Faster Than Lists.
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

**Numpy Installation**

pip install numpy

In [ ]:
import numpy as np

In [ ]:
# array() function is used create arrays

In [ ]:
# 1-D ARRAY
a = np.array([1,2,3,4])   # 1-D - An array that has 0-D arrays as it's elements
print(a)

[1 2 3 4]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
# Dimension in arrays
# 0-D or scalar array- elements in an array
zero_dim = np.array(600)
print(zero_dim)

600


In [ ]:
# 2-D array - An array that has 1-D arrays as it's elements.
two_dim = np.array([[1,2,4,7],[10,11,20,30],[0,0,0,0]])
print(two_dim)

[[ 1  2  4  7]
 [10 11 20 30]
 [ 0  0  0  0]]


In [ ]:
# 3-D array - An array that has 2-D arrays as it's elements.
three_dim = np.array([[[10,20,30],[40,50,60]],[[10,20,30],[40,50,60]]])
print(three_dim)

[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 60]]]


In [ ]:
# 4-D array - An array that has 3-D arrays as it's elements.
four_dim = np.array([[[[1,2,3]],[[4,5,6]]],[[[4,5,6]],[[7,8,9]]]])
four_dim

array([[[[1, 2, 3]],

        [[4, 5, 6]]],


       [[[4, 5, 6]],

        [[7, 8, 9]]]])

In [ ]:
# ndim - to check the dimensions of an array
print(zero_dim.ndim)
print(a.ndim)
print(two_dim.ndim)
print(three_dim.ndim)


0
1
2
3


In [ ]:
# ndmin argument - to define the number of dimensions
b = np.array([10,15,20,15,20],ndmin=8)
print(b)
print(b.ndim)

[[[[[[[[10 15 20 15 20]]]]]]]]
8


In [ ]:
# ARRAY INDEXING
# positive indexing - start :0 ----> end : length(number of items)-1
# array_name[index]

# SLICING:
# array_name[start_index:end_index:step]  end_index excluded

In [ ]:
c = np.array([11,22,33,44,55,66,77,88,99])
print(c[0])
print(c[2])

11
33


In [ ]:
print(c[1:7:1])

[22 33 44 55 66 77]


In [ ]:
print(c[:])

[11 22 33 44 55]


In [ ]:
print(c[1:7:3])

[22 55]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0])
print(arr[1])

[1 2 3]
[4 5 6]


In [ ]:
print(arr[0,2])

3


In [ ]:
print(arr[1,1])

5


In [ ]:
print(arr[0,1:])

[2 3]


In [ ]:
arr1 = np.array([[["a","b","b"],["c","d","c"]],[["e","f","f"],["g","h","g"]]])
print(arr1[0])

[['a' 'b' 'b']
 ['c' 'd' 'c']]


In [ ]:
print(arr1[1])

[['e' 'f']
 ['g' 'h']]


In [ ]:
print(arr1[0,1])

['c' 'd']


In [ ]:
print(arr1[0,1,1])

d


In [ ]:
print(arr1[1,1,1:])

['h' 'g']


In [ ]:
print(arr1[-1,-2,-3])

e


In [ ]:
# NUmpy array
# pip install numpy

**Data Types in NumPy**

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

The NumPy array object has a property called **dtype** that returns the data type of the array

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [ ]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


**Creating Arrays With a Defined Data Type**

We use the **array()** function to create arrays, this function can take an optional argument: **dtype** that allows us to define the expected data type of the array elements.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
arr = np.array([1, 0, 3, 0], dtype='bool')

print(arr)
print(arr.dtype)

[ True False  True False]
bool


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='f')

print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


In [ ]:
arr = np.array([1.1, 2.9, 3.5, 4.7], dtype='i')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


The **astype()** function creates a copy of the array, and allows you to specify the data type as a parameter.

In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1]) #original array

newarr = arr.astype('bool') #updated array

print("original array: ",arr)
print("original array dtype: ",arr.dtype)
print("updated array: ",newarr)
print("updated array dtype: ",newarr.dtype)

original array:  [1.1 2.1 3.1]
original array dtype:  float64
updated array:  [ True  True  True]
updated array dtype:  bool


In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [ ]:
# COPY AND VIEW FUNCTIONS : used to copy an array

# copy:  the copy is a new array. It owns the data. Any changes made to the original array does not affect the copy array.
#  Any changes made to the copy array does not affect the original array.
# copy() function
# view : it is just view of the array. It does not owns the data. Any changes made to the original array will affect the view array and vise versa.
# view() function

In [ ]:
fruit = np.array(['apple','orange','kiwi'])
print("Original array: ",fruit)

new_fruit = fruit.copy()
print("copy array: ",new_fruit)

print(new_fruit.base)

Original array:  ['apple' 'orange' 'kiwi']
copy array:  ['apple' 'orange' 'kiwi']
None


In [ ]:
fruit[1]='cherry'
print('after updation:')
print('Original array: ',fruit)
print('Copy array :',new_fruit)

after updation:
Original array:  ['apple' 'cherry' 'kiwi']
Copy array : ['apple' 'orange' 'kiwi']


In [ ]:
fruit = np.array(['apple','orange','kiwi'])
print("Original array: ",fruit)

new_fruit = fruit.view()
print("view array: ",new_fruit)

print(new_fruit.base)

Original array:  ['apple' 'orange' 'kiwi']
view array:  ['apple' 'orange' 'kiwi']
['apple' 'orange' 'kiwi']


In [ ]:
fruit[1]='cherry'
print('after updation:')
print('Original array: ',fruit)
print('view array :',new_fruit)

after updation:
Original array:  ['apple' 'cherry' 'kiwi']
view array : ['apple' 'cherry' 'kiwi']


In [ ]:
new_fruit[1]='banana'
print('AFTER UPDATION:')
print('original array:',fruit)
print('view array: ',new_fruit)

AFTER UPDATION:
original array: ['apple' 'banana' 'kiwi']
view array:  ['apple' 'banana' 'kiwi']


NumPy array has the attribute **base** that returns **None** if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
# SHAPE OF AN ARRAY
# It is the number of elements in each dimension.
# Numpy array has an attribute called shape that returns the shape of an array. It returns a tuple with index having the number of corresponding elements.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)

(6,)


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])  # 2 elements
print(arr1)
print(arr1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
arr2 = np.array([[[1,2],[3,4]],[[1,2],[5,6]],[[5,6],[8,9]]]) #3 elements
print(arr2.shape)  #(3,2,2)

(3, 2, 2)


In [ ]:
arr3 = np.array([[[[1,2,3,4]]],[[[1,2,3,4]]]]) #2
print(arr3.shape) #(2,1,1,4)

(2, 1, 1, 4)


In [ ]:
# Reshaping of an array : changing the shape of an array
# reshape() function

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])   #2D- 4*3 , 3*4, 6*2, 2*6, 1*12, 12*1   3d - (3,2,2), (2,3,2),(2,2,3),(4,3,1)
print(a)
print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [ ]:
new_a = a.reshape(4,3)
new_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
new_a = a.reshape(2,6)
new_a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
new_a = a.reshape(1,12)
new_a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
new_a = a.reshape(12,1,1,1)
new_a

In [ ]:
new_a = a.reshape(4,3,1)
new_a

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [ ]:
new_a = a.reshape(2,2,-1)
new_a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
new_a = a.reshape(4,-1)
new_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
new_a = a.reshape(2,2,-1)
new_a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
print(new_a.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# MULTIDIMENSIONAL ARRAY TO 1-D ARRAY CONVERSION
# reshape(-1)

In [ ]:
b = np.array([[[1,2,3,4]],[[4,5,6,7]]])
print(b.ndim)

3


In [ ]:
b_one = b.reshape(-1)
print(b_one)

[1 2 3 4 4 5 6 7]


**NumPy Array Iterating**

Iterating means going through elements one by one.


In [ ]:
# Iterating 1-D Array
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [ ]:
# Iterating 2-D Array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
arr = np.array([[[1,2]],[[3,4]]])
for i in arr:print(i)

[[1 2]]
[[3 4]]


In [ ]:
# Iterate on a n-D array it will go through n-1th dimension one by one.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
# Iterating 3-D Array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
a = np.array([[[[[1,2,3,4,5]]]]])
for i in a:
  for j in i:
    for k in j:
      for l in k:
        for g in l:
          print(g)

1
2
3
4
5


**Iterating Arrays Using nditer()**

The function **nditer()** is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration.

In [ ]:
import numpy as np

arr = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


**Enumerated Iteration Using ndenumerate()**

Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


**NumPy Joining Array**

Joining means putting contents of two or more arrays in a single array.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [ ]:
# Join two arrays

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2),axis=0)

print(arr)

[1 2 3 4 5 6]


In [ ]:
# Join two 2-D arrays along rows (axis=1):

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
# print(arr1)

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2),axis=1)

print(arr)

[[1 2]
 [3 4]]
[[1 2 5 6]
 [3 4 7 8]]


**Joining Arrays Using Stack Functions**

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


**NumPy Splitting Array**

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

newarr = np.array_split(arr, 3)

print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2, 3]), array([4, 5]), array([6, 7])]
[1 2 3]
[4 5]
[6 7]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 2)

print(newarr)
# print(newarr[0])
new = newarr[0]
print(new[1])

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10],
       [11, 12]])]
[3 4]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(arr)
newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


**NumPy Searching Arrays**

Search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 14, 24, 4])

x = np.where(arr >= 10)

print(x)

(array([5, 6]),)


In [ ]:
arr = np.array([10, 2, 3, 4, 50, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([2, 6]),)


**Search Sorted**

There is a method called **searchsorted()** which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [ ]:
import numpy as np

arr = np.array([6, 7, 2, 8, 9])  # 2,6,7,8,9

x = np.searchsorted(arr, 2)

print(x)

print(np.__version__)

0
1.22.4


In [ ]:
arr = np.array([1, 3, 5, 7])   # 1 3 5 6 7

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


**Sorting Arrays**

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [ ]:
import numpy as np
arr = np.array([3, 2, 0, 1])
y = np.sort(arr)[::-1]
# print(np.sort(arr))
y


array([3, 2, 1, 0])

In [ ]:
arr = np.array(['banana', 'Cherry', 'apple'])
print(np.sort(arr))

['Cherry' 'apple' 'banana']


In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


**Filtering Arrays**

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

# array_name[boolean index list]
newarr = arr[x]

print(newarr)

[41 43]


In [ ]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0   # boolean index list

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [ ]:
new_arr = arr>3
print(new_arr)

print(arr[new_arr])

[False False False  True  True  True  True]
[4 5 6 7]


**Numpy Random Module**

Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

NumPy offers the random module to work with random numbers.

The random module's **randint()** method returns a random integer.

In [ ]:
# Generate a random integer from 0 to 100:
from numpy import random

x = random.randint(100)  #0 - 99

print(x)

3


**Generate Random Float**

The random module's **rand()** method returns a random float between 0 and 1.

In [ ]:
# Generate a random float from 0 to 1:

from numpy import random

x = random.rand()

print(x)

0.8898619633266104


The **randint()** method takes a size parameter where you can specify the shape of an array.


In [ ]:
# Generate a 1-D array containing 5 random integers from 0 to 100:

from numpy import random

x=random.randint(10, size=(5))  #1-D

print(x)

[6 9 6 7 0]


In [ ]:
x = random.randint(100, size=(3, 5))

print(x)

[[66 27 52  2 30]
 [42 98 42 23  0]
 [55 81 43 33 84]]


In [ ]:
x = random.rand(3, 5, 2)  #2-d

print(x)

[[[0.69260361 0.8250702 ]
  [0.6381576  0.05851948]
  [0.93393594 0.24638887]
  [0.08274509 0.91826035]
  [0.78130326 0.40476881]]

 [[0.98977583 0.23198801]
  [0.15773131 0.65853608]
  [0.56869126 0.31154593]
  [0.73430721 0.90325592]
  [0.81794088 0.71995188]]

 [[0.56646503 0.22314408]
  [0.70401962 0.97045859]
  [0.27656658 0.22077905]
  [0.34756554 0.79592405]
  [0.10968477 0.26598117]]]


**Generate Random Number From Array**

The **choice()** method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

In [ ]:
x = random.choice([3, 5, 7, 9])

print(x)

9


In [ ]:
x = random.choice([3, 5, 7, 9], size=(3, 5))   # [0,0.7,0.2,0.1]

print(x)

[[7 5 7 3 3]
 [3 3 9 5 7]
 [9 7 5 3 9]]


**Data Distribution**

Data Distribution is a list of all possible values, and how often each value occurs.

A random distribution is a set of random numbers that follow a certain probability density function.

The choice() method allows us to specify the probability for each value.

The probability is set by a number between 0 and 1, where 0 means that the value will never occur and 1 means that the value will always occur.

In [ ]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(10))

print(x)

[7 3 7 7 5 5 7 7 7 7]


In [ ]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.0, 0.6], size=(3, 5))

print(x)

[[9 5 9 9 3]
 [9 9 5 9 3]
 [9 9 9 9 5]]


**Random Permutations**

The NumPy Random module provides two methods for this: shuffle() and permutation().

**Shuffling Arrays**

Shuffle means changing arrangement of elements in-place. i.e. in the array itself.

The shuffle() method makes changes to the original array.

Randomly shuffle elements of following array:


In [ ]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[4 5 2 1 3]


The **permutation()** method returns a re-arranged array (and leaves the original array un-changed).

In [ ]:
# Generate a random permutation of elements of following array:

from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

per_arr = random.permutation(arr)
print(arr)
print(per_arr)

[1 2 3 4 5]
[5 1 3 2 4]


**STATISTICAL FUNCTIONS**

**Mean** - The average value

**Median** - The mid point value

**Mode** - The most common value

In [ ]:
# NumPy mean() method to find the average speed:

import numpy

speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]

x = numpy.mean(speed)

print(x)

89.76923076923077


In [ ]:
#, N,umPy median() method to find the middle value
# [7,2,9,5,1 6] ----> [1,2,5,6,7,9] --- > 6
import numpy

# speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]

# x = numpy.median(speed)

x = numpy.median([7,2,9,5,6])

print(x)

6.0


In [ ]:
# SciPy mode() method to find the number that appears the most:
import warnings
warnings.filterwarnings('ignore')

from scipy import stats

speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]

x = stats.mode(speed)

print(x)

ModeResult(mode=array([86]), count=array([3]))


**Standard Deviation**

Standard deviation is a number that describes how spread out the values are.

A low standard deviation means that most of the numbers are close to the mean (average) value.

A high standard deviation means that the values are spread out over a wider range.

In [ ]:
# NumPy std() method to find the standard deviation:

import numpy

speed = [32,111,138,28,59,77,97]

x = numpy.std(speed)

print(x)

37.84501153334721


**Variance**

Variance is another number that indicates how spread out the values are.

The square root of the variance is standard deviation.

In [ ]:
# NumPy var() method to find the variance:

import numpy

speed = [32,111,138,28,59,77,97]

x = numpy.var(speed)

print(x)

1432.2448979591834


In [ ]:
from math import sqrt
sqrt(x)

37.84501153334721

# **Percentiles**

Percentiles are used in statistics to give you a number that describes the value that a given percent of the values are lower than.

In [ ]:
# NumPy percentile() method to find the percentiles:

import numpy

ages = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31]

x = numpy.percentile(ages, 80)

print(x)

48.0


In [ ]:
ages = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31]

x = numpy.percentile(ages, 90)

print(x)

61.0


In [ ]:
# [0 0 0 0 0 0 0 0 0 0]
# zeros()

x = np.zeros((2,6),dtype=int)
print(x)
print(x.dtype)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]
int64


In [ ]:
y = np.ones((2,3),dtype=int)
print(y)

[[1 1 1]
 [1 1 1]]


In [ ]:
# linspace : generate a numpy array wih specified start and end(inclusive), number of values

z = np.linspace(0,2,5)
print(z)

[0.  0.5 1.  1.5 2. ]


In [ ]:
# sum

ar = np.array([1,2,3,4])
sum_ar = np.sum(ar)
sum_ar

10

In [ ]:
# max

ar = np.array([1,2,3,4])
max_ar = np.max(ar)
max_ar

4

In [ ]:
# min

ar = np.array([1,2,3,4])
min_ar = np.min(ar)
min_ar

1